config/routes.rb
TTS::Application.routes.draw do
  get "story/index"

  resources :stories
  

  root :to => 'stories#index'

end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :text
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	def new

  end

  def create
    @story = Story.new(params[:story])

    @story.save
    redirect_to @story
  end

  def show
    @story = Story.find(params[:id])
  end

  def index
   @story= Story.all
  end

  private
    def story_params
      params.require(:story).permit(:text)
    end
end

app/controllers/story_controller.rb
class StoryController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/story_helper.rb
module StoryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TTS</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stories/index.html.erb
<% @story.each do |story| %>
 <div><%= story.text %></div> 
<% end %>

app/views/stories/new.html.erb
<h1>Holla, new post!</h1>

<%= form_for :story, url: stories_path do |f| %>
  <p>
    <%= f.label :text %></br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/stories/show.html.erb
<p>
  <strong>#tweetsizedstory</strong>
  <%= @story.text %>
</p>

app/views/story/index.html.erb
<h1>Holla, Amigos!</h1>